"""make harvester_uid unique

Revision ID: 3f4c0fc54631
Revises: 10380660ec58
Create Date: 2024-04-29 19:09:35.315928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4c0fc54631'
down_revision = '10380660ec58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_equipment_harvester_uid', table_name='equipment')
    op.create_index(op.f('ix_equipment_harvester_uid'), 'equipment', ['harvester_uid'], unique=True)
    op.drop_index('ix_herb_harvester_uid', table_name='herb')
    op.create_index(op.f('ix_herb_harvester_uid'), 'herb', ['harvester_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_herb_harvester_uid'), table_name='herb')
    op.create_index('ix_herb_harvester_uid', 'herb', ['harvester_uid'], unique=False)
    op.drop_index(op.f('ix_equipment_harvester_uid'), table_name='equipment')
    op.create_index('ix_equipment_harvester_uid', 'equipment', ['harvester_uid'], unique=False)
    # ### end Alembic commands ###
