"""test revision 3

Revision ID: 4b6b6648958f
Revises: c4e43d6b8943
Create Date: 2024-01-20 16:20:11.996291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6b6648958f'
down_revision = 'c4e43d6b8943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('camera_number', sa.String(length=26), nullable=False))
    op.drop_index('ix_camera_camera_mac', table_name='camera')
    op.create_index(op.f('ix_camera_camera_number'), 'camera', ['camera_number'], unique=False)
    op.drop_column('camera', 'camera_mac')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('camera_mac', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_camera_camera_number'), table_name='camera')
    op.create_index('ix_camera_camera_mac', 'camera', ['camera_mac'], unique=False)
    op.drop_column('camera', 'camera_number')
    # ### end Alembic commands ###
