"""test revision

Revision ID: 904e772bf42a
Revises: 
Create Date: 2024-01-20 16:10:23.735754

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '904e772bf42a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_mac', sa.String(length=32), nullable=False),
    sa.Column('camera_name', sa.String(length=50), nullable=False),
    sa.Column('agent_uid', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_agent_uid'), 'camera', ['agent_uid'], unique=False)
    op.create_index(op.f('ix_camera_camera_mac'), 'camera', ['camera_mac'], unique=True)
    op.create_index(op.f('ix_camera_id'), 'camera', ['id'], unique=False)
    op.create_table('nx_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_uid', sa.String(length=50), nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nx_server_agent_uid'), 'nx_server', ['agent_uid'], unique=False)
    op.create_index(op.f('ix_nx_server_id'), 'nx_server', ['id'], unique=False)
    op.create_index(op.f('ix_nx_server_system_id'), 'nx_server', ['system_id'], unique=False)
    op.create_geospatial_table('license_plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('agent_uid', sa.String(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('live_capture_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gps_location', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_license_plate_gps_location', 'license_plate', ['gps_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_license_plate_agent_uid'), 'license_plate', ['agent_uid'], unique=False)
    op.create_index(op.f('ix_license_plate_camera_id'), 'license_plate', ['camera_id'], unique=False)
    op.create_index(op.f('ix_license_plate_id'), 'license_plate', ['id'], unique=False)
    op.create_index(op.f('ix_license_plate_region'), 'license_plate', ['region'], unique=False)
    op.create_index(op.f('ix_license_plate_uuid'), 'license_plate', ['uuid'], unique=False)
    op.create_table('nx_cameras_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('nx_camera_id', sa.String(length=50), nullable=False),
    sa.Column('nx_server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nx_server_id'], ['nx_server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nx_cameras_map_id'), 'nx_cameras_map', ['id'], unique=False)
    op.create_index(op.f('ix_nx_cameras_map_nx_camera_id'), 'nx_cameras_map', ['nx_camera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nx_cameras_map_nx_camera_id'), table_name='nx_cameras_map')
    op.drop_index(op.f('ix_nx_cameras_map_id'), table_name='nx_cameras_map')
    op.drop_table('nx_cameras_map')
    op.drop_index(op.f('ix_license_plate_uuid'), table_name='license_plate')
    op.drop_index(op.f('ix_license_plate_region'), table_name='license_plate')
    op.drop_index(op.f('ix_license_plate_id'), table_name='license_plate')
    op.drop_index(op.f('ix_license_plate_camera_id'), table_name='license_plate')
    op.drop_index(op.f('ix_license_plate_agent_uid'), table_name='license_plate')
    op.drop_geospatial_index('idx_license_plate_gps_location', table_name='license_plate', postgresql_using='gist', column_name='gps_location')
    op.drop_geospatial_table('license_plate')
    op.drop_index(op.f('ix_nx_server_system_id'), table_name='nx_server')
    op.drop_index(op.f('ix_nx_server_id'), table_name='nx_server')
    op.drop_index(op.f('ix_nx_server_agent_uid'), table_name='nx_server')
    op.drop_table('nx_server')
    op.drop_index(op.f('ix_camera_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_camera_mac'), table_name='camera')
    op.drop_index(op.f('ix_camera_agent_uid'), table_name='camera')
    op.drop_table('camera')
    # ### end Alembic commands ###
