"""test revision 2

Revision ID: c4e43d6b8943
Revises: 904e772bf42a
Create Date: 2024-01-20 16:12:08.574984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e43d6b8943'
down_revision = '904e772bf42a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nx_cameras_map_id', table_name='nx_cameras_map')
    op.drop_index('ix_nx_cameras_map_nx_camera_id', table_name='nx_cameras_map')
    op.drop_table('nx_cameras_map')
    op.drop_index('ix_nx_server_agent_uid', table_name='nx_server')
    op.drop_index('ix_nx_server_id', table_name='nx_server')
    op.drop_index('ix_nx_server_system_id', table_name='nx_server')
    op.drop_table('nx_server')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nx_server',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('nx_server_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('agent_uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('system_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='nx_server_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_nx_server_system_id', 'nx_server', ['system_id'], unique=False)
    op.create_index('ix_nx_server_id', 'nx_server', ['id'], unique=False)
    op.create_index('ix_nx_server_agent_uid', 'nx_server', ['agent_uid'], unique=False)
    op.create_table('nx_cameras_map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nx_camera_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nx_server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], name='nx_cameras_map_camera_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nx_server_id'], ['nx_server.id'], name='nx_cameras_map_nx_server_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nx_cameras_map_pkey')
    )
    op.create_index('ix_nx_cameras_map_nx_camera_id', 'nx_cameras_map', ['nx_camera_id'], unique=False)
    op.create_index('ix_nx_cameras_map_id', 'nx_cameras_map', ['id'], unique=False)
    # ### end Alembic commands ###
